### ISSUE TITLE
Improper HTML with spoiler tags

### ISSUE THREAD

**Issue by marrus-sh** [hometown-fork/hometown#10]
I recently noticed that Hometown fork wraps the “Show More” button on toots with CWs (spoilers) in a `<div>`: <https://github.com/hometown-fork/hometown/blob/hometown-dev/app/javascript/mastodon/components/status_content.js#L226>.

This makes the “Show More” button always appear on the line *following* the spoiler content, instead of inline with it.

I actually like this behaviour, but there is a problem: Nesting a `<div>` inside of a `<p>` tag is non­‑conforming HTML. `<span style={{ display: "block" }}>` should be used instead.

(For reference, upstreamʼs equivalent code is here: <https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/components/status_content.js#L221>.)

**Comment by dariusk** [comment]
Hi, thanks so much for this and your other well-documented issues. I expect this to be resolved in 1.0.2 (I just released 1.0.1 which adds some new themes that were in PR).
