### ISSUE TITLE
Hashtag suggestions are removing CamelCase

### ISSUE THREAD

**Issue by rkingett** [hometown-fork/hometown#1049]
First, it's worth noting that [Mastodon has this proposed fix](https://github.com/tootsuite/mastodon/pull/16460) but I was hoping this fork would be more receptive to fixing this issue if that PR gets rejected.

## Steps to reproduce

1. Compose a new toot.
2. Enter a hashtag with CamelCase but do not complete the hashtag.
3. observe the autocomplete suggestions are all lower case.

## Expected behavior.

I'd like all hashtags to be suggested with CamelCase by default. This way, it helps make the instances more accessible and also boosting user experience.

If a hashtag is suggested, the suggestion should only be in CamelCase.

**Comment by nevillepark** [comment]
I've noticed this and it's rather annoying. Since learning that it's better for screenreaders I've been putting hashtags in camel case (e.g. `#CatsOfMastodon`) and it's annoying to have the drop-down put it in lowercase.

**Comment by weex** [comment]
Hey, I authored the aforementioned patch and was curious to try and PR it here, but GitHub doesn't support having more than one linked fork on an account. So I cloned hometown separately and create an unlinked fork with the patch applied.

https://github.com/weex/hometown with the branch `ignore-hashtag-case` has the patch if anyone knows how to extract a patch and apply it to their hometown fork.

**Comment by dariusk** [comment]
This landed in Mastodon 3.5.2 and thus was fixed in Hometown v1.0.5+3.5.2!

**Comment by bixfrankonis** [comment]
Related but separate issue: if you use CamelCase when adding a featured hashtag to your profile but the system already knows that hashtag and has seen it as not CamelCase, it removes your own CamelCase and adds the non-CamelCase version instead.

**Comment by dariusk** [comment]
There's an open bug on Mastodon for this: https://github.com/mastodon/mastodon/issues/18184
