### ISSUE TITLE
Add alfazema.club to the list of instances

### ISSUE THREAD

**Issue by pedrolucasp** [hometown-fork/hometown#1050]
It's been over 5 months I have setup a personal instance at alfazema.club and it's been a blast, so I think it made sense to share this instance here as well :)

It's a more generalist instance, focusing on friendly discussions, tech, with no space for bigotry. Most toots are in english, but it's opened for latinx folks (I'm a brazilian :wave: 😃 ). As I'm the sole user, I didn't bother writing a CoC or something along the lines yet, but I'm open to construct one if more users join the instance.

Accepting new users? yes (with review)

**Comment by ghost** [comment]
Done: https://github.com/hometown-fork/hometown/wiki/Hometown-servers/6e13f09cab7218ad7cf15872f1e65854eb859426
