### ISSUE TITLE
[feature] limited federation mode extra features

### ISSUE THREAD

**Issue by noiob** [hometown-fork/hometown#1143]
### Background

Hi, I'm the admin of awoo.space, and we've been running the instance in allowlist mode since before that became a mainline feature. When the feature rolled out I decided to rebuild it on top of the mainline feature for easier maintainability. It's sad to see how little thought was put into the mainline feature even though it could be very useful, especially for small instances

### Pitch

@AloeSlasher, who's an admin at rage.love, approached me with questions about the built-in federation mode. Out of that conversation came the idea to add the option to [still have public profile/toot pages](https://github.com/noiob/awoospace/commit/cc7845e790461ea5c9fe16618c6a272b7b257669) and the option to [publicly display the instance allowlist](https://github.com/noiob/awoospace/commit/f05ab3e08f7ffc5e660a6e91b97309f4ff0e31a9) to hometown. Ideally I think these would be behind an additional feature flag each.

I'd like to use this issue to gauge interest and get some input over how to best include these features so more people can utilize allowlist federation

**Comment by rscmbbng** [comment]
This PR works in a similar direction by enabling the display of the about/more page in limited federation mode:  https://github.com/hometown-fork/hometown/pull/966

**Comment by exstral** [comment]
Hi @noiob ! Thank you so much for instance inspiration and these code changes we are still using on queer.haus ! As @rscmbbng already mentioned I've created a pull request with them in #966 

Along the years I've rewritten my git history a lot to keep up with hometown releases so your commit author has been lost. Can easily be restored if you wish :)

That pull request is brute force though, the change is not hidden behind a feature flag or a setting, it is just applied.

**Comment by dariusk** [comment]
Closing since #966 addresses at least some of this and will be in `v.1.0.6+3.5.2`.
