### ISSUE TITLE
Inline image previews are... awkward

### ISSUE THREAD

**Issue by tyrosinase** [hometown-fork/hometown#1145]
### Expected behaviour

Images should thumbnail reasonably even if they're inline.

![image](https://user-images.githubusercontent.com/9473609/146422152-c2aaf323-bdf1-46dc-852d-cd12aa1a92d7.png) (vanilla masto)

### Actual behaviour

Skyscrapers! We got skyscrapers everywhere!

![image](https://user-images.githubusercontent.com/9473609/146422279-f880d0d5-b609-40b9-98b7-0d2106a085d5.png)

Off the screen even at 30% zoom: the images also get thumbnailed at the bottom, just like vanilla. Ideally the images should get left inline but thumbnailed (note that there's one image in the thumbnails that isn't an inline one; if inlines get size-corrected the thumbnails shouldn't be removed altogether).

### Steps to reproduce the problem

Look at something like https://silverseams.com/2021/12/christmas-baking/ (a WordPress blog with the ActivityPub plugin, FWIW) in a Hometown install.

### Specifications

Skyscraper screenshot is from weirder.earth, which is running v1.0.5. The correct[er] screenshot is from mastodon.art, which is a masto.host'ed vanilla v3.4.4. Both are as viewed from Linux Firefox.

**Comment by tyrosinase** [comment]
(on the plus side, Hometown does a better job of pulling in the author avatar than masto.host)

**Comment by dariusk** [comment]
Fix will be in `v1.0.6+3.5.2`! Thanks!

**Comment by tyrosinase** [comment]
(of course nowadays that blog isn't WordPress and doesn't have ActivityPub, but I'm sure there's another one out there that still is and does.)

**Comment by dariusk** [comment]
The blog post was at least cached in my server so I was still able to view it and debug!

**Comment by tyrosinase** [comment]
Federation ftw!
