### ISSUE TITLE
Visually distinguish DMs in Fairy Floss theme

### ISSUE THREAD

**Issue by hughrun** [hometown-fork/hometown#1146]
### Pitch

The Macaron theme helpfully changes the background colour of Direct (private) messages to visually distinguish them from other more public messages. It appears to be the only theme that does this. I would love for the Fairy Floss (dark pastel) theme to do something similar.
### Motivation

Especially for users using the single-column view, it is very easy to not notice that a DM is a DM rather than a public post. This is confusing, but also a little dangerous: users can accidentally bring a third user into the allegedly private conversation when they think they are simply tagging in a user to a public conversation.

**Comment by dariusk** [comment]
I believe I actually fixed this in the last few months, which means the v1.0.5+3.4.6 release that came out yesterday should work in Fairy Floss! See this screenshot:

![image](https://user-images.githubusercontent.com/266454/152585627-9e4a49ec-1d1f-4012-9cce-eb5c4000f0fb.png)
