### ISSUE TITLE
Prepare for critical security patch Thursday

### ISSUE THREAD

**Issue by aphick** [hometown-fork/hometown#1148]
https://github.com/mastodon/mastodon/releases/
> Mastodon v3.3.2 and v3.4.6 will be released on Thursday, February 3rd, between 13:00 and 15:00 UTC, fixing a variety of bugs, including a **critical security issue.**
>
It's been a while since there was a hometown release and it seems like this might be important to do in a timely manner.

**Comment by rscmbbng** [comment]
I also came here to mention this. Is there any way we can help making sure we can upgrade swiftly?

**Comment by ghost** [comment]
@dariusk is the sole owner of the repo, so there isn't much to do right now. I hope you'll have some time to work on this in the following days!

And we can still draft something to open maintainer work to others if you'd like. :)

**Comment by dariusk** [comment]
Yes! I am working with @garbados on a soon-to-come release!

**Comment by dariusk** [comment]
Hi all, release with the security patch coming after my work day today.

**Comment by dariusk** [comment]
Okay, `v1.0.5+3.4.6` is released! [Get it here!!!](https://github.com/hometown-fork/hometown/releases/tag/v1.0.5%2B3.4.6)

**Comment by rscmbbng** [comment]
Thanks for the quick response @dariusk!
