### ISSUE TITLE
Appreciating boosts

### ISSUE THREAD

**Issue by ketefoy** [hometown-fork/hometown#1149]
I would like a button to thank someone for boosting a toot. Sometimes, a boost is so helpful that I want to reply and thank that person, but I feel like a button is more appropriate.

**Comment by dariusk** [comment]
This is a good idea but kind of out of the scope of Hometown. I feel like the way to do this right now is to @ the person and thank them. To implement this would require pretty significant engineering and UX work that would be too much divergence from Mastodon for this small team to maintain. I encourage you to submit this to the Mastodon project as a feature suggestion.
