### ISSUE TITLE
Connection to Fedilab app fails

### ISSUE THREAD

**Issue by 1frn0** [hometown-fork/hometown#1152]
### Expected behaviour

Fedilab should detect the server. It worked fine before the latest security update. Regular Mastodon servers are detected.

### Actual behaviour

Fedilab gets stuck on the instance selection screen.

### Steps to reproduce the problem

Open Fedilab app, type a Hometown instance server domain, tap "Connect" button.

### Specifications

The server is running the latest version of Hometown. Fedilab is running on Android 12.

EDIT: Cross-posted to [Fedilab repo](https://framagit.org/tom79/fedilab/-/issues/548).

**Comment by dariusk** [comment]
So.... I have no idea how Fedilab works but will try and fix this for an upcoming release.

**Comment by dariusk** [comment]
Closing because I can no longer reproduce this with the latest Fedilab and the latest Hometown.
