### ISSUE TITLE
Merging OpenID Connect support?

### ISSUE THREAD

**Issue by decentral1se** [hometown-fork/hometown#1153]
### Pitch

https://github.com/mastodon/mastodon/pull/16221 will be merged One Day :tm: (OpenID Connect support)

Can that then be rebased in here? I'm making this issue to check that is something that Hometown wants. I hope so.

 I'm maintaining a fork of hometown with this patch merged in via a very hairy git cherry picking routine which I don't think I can keep up as things are getting quite divergent in the changes between the PR rebasing & forking stuff.

### Motivation

OpenID Connect is what we need for not having users create n+1 user accounts for each service in an existing online community that wants to make use of Hometown.

**Comment by decentral1se** [comment]
In the meantime, I've just managed to publish `decentral1se/hometown:v1.0.5_3.6.0_openid-sso` :+1: 

(I just realised I borked the tag, should be `v1.0.5_3.4.6_openid-sso` :facepalm: but building the masto container takes approximately 172 hours so I'm not doing it again...)

**Comment by decentral1se** [comment]
It has been merged finally today :partying_face: 

https://github.com/mastodon/mastodon/pull/16221

**Comment by decentral1se** [comment]
And available via release in https://github.com/mastodon/mastodon/releases/tag/v3.5.0 :rocket:

**Comment by dariusk** [comment]
Great! This should have now landed in `v1.0.5+3.5.2`.
