### ISSUE TITLE
Automatic post deletion didn't fork to Hometown

### ISSUE THREAD

**Issue by rkingett** [hometown-fork/hometown#1155]
In Mastodon v3.4.6 and later, users, while logged in, can have the system automatically delete posts based on certain criteria. The tool can be found at the below URL in Mastodon.

https://instance.name/statuses_cleanup

[Here is where it was merged into Mastodon](https://github.com/mastodon/mastodon/pull/16529)

### Expected behaviour

When a user logs in, there should be a link in the profile navigation area to a page that says auto delete posts or automatic post removal, like there is in Mastodon.

### Actual behaviour

After logging into any Hometown instance, this option does not appear anywhere. Trying to go to the above URL by replacing the instance name does not work. The page cannot be found.

### Steps to reproduce the problem

After logging in, try to go to https://instance.name/statuses_cleanup

### Specifications

Hometown v3.4.6+1.0.5

**Comment by MaybeThisIsRu** [comment]
So I tracked this down the other day too. While it was merged into the `main` branch, it wasn't released as an official feature until version 3.5.0 on Mastodon. And that version of Mastodon is yet to be merged and released on Hometown. I think it's in progress though. So once Hometown has a parity release with Mastodon 3.5.0 or 3.5.1, it should be available.

**Comment by dariusk** [comment]
Fixed in release `v1.0.5+3.5.2`!
