### ISSUE TITLE
Mastodon 3.5.2 Parity

### ISSUE THREAD

**Issue by techknowlogick** [hometown-fork/hometown#1160]
### Pitch

Mastodon 3.5.1 is out, this is an issue to track parity with it

**Comment by dariusk** [comment]
We are up to 3.5.2! I will be announcing in the morning my local time (in about 12 hours) so that I can be available to answer people's questions etc.

https://github.com/hometown-fork/hometown/releases/tag/v1.0.5%2B3.5.2
