### ISSUE TITLE
Yunohost package?

### ISSUE THREAD

**Issue by nevillepark** [hometown-fork/hometown#1161]
### Pitch

For the relatively non-technical (like me), [Yunohost](yunohost.org/) makes it much easier for people to self-host apps, even more so than solutions like DigitalOcean apps or Docker packages. There is a [Mastodon package for Yunohost](https://github.com/YunoHost-Apps/mastodon_ynh), but as per issue #16, there isn't a way to migrate it to hometown. (There also doesn't seem to be a way to just install hometown without having installed Mastodon first?) It would be nice if there were a simple way to run a hometown instance with Yunohost.

### Motivation

Platforms like hometown, which are really good for small communities, should be ideally suited for self-hosting—but right now, they're not. Creating a hometown package for software like Yunohost would make it possible for even more people to [run their own social networks](https://runyourown.social).

**Comment by dariusk** [comment]
This is a great idea but I have noticed that with these things, you need someone who is dedicated to constantly updating the packages. Basically it's a really useful feature but I can't promise that I will keep it up to date. If someone out there wants to maintain a package that would rule.

**Comment by nevillepark** [comment]
Okay, thanks! I'll keep a look out for any hometown/Yunohost users who might be interested in helping.

**Comment by badrihippo** [comment]
I'm interested in running a Hometown instance on YunoHost, which means I'll also end up updating the package if necessary when a new version comes out. If I understand right, setting up Hometown is 99.99% identical to setting up Mastodon, right?

If so, I can clone the existing [`mastodon_ynh`](https://github.com/YunoHost-Apps/mastodon_ynh) package and update it to use Hometown, as a starting point. Would be happy to maintain it in future if I had one other backup person (eg. for times I'm not available and there's an urgent security update)
