### ISSUE TITLE
On profile, <p> margin-bottom is missing

### ISSUE THREAD

**Issue by thomasmdickinson** [hometown-fork/hometown#1162]
Apologies if this has been captured elsewhere but I did not spot it. I think _this_ is a Hometown issue and not a Mastodon issue, for reasons described below.

### Expected behaviour

Paragraphs in status should have a 20px margin bottom on the public profile (http://foo.bar/@user), as they do on the accounts page (https://foo.bar/web/accounts/108222192886738962)

### Actual behaviour

As of right now there is no bottom margin on the profile.

For example: Status appears correctly when l am logged in and view the account at https://labyrinth.social/web/accounts/108222192886738962

![CleanShot 2022-05-05 at 19 33 29](https://user-images.githubusercontent.com/11141120/167043720-baa22b04-785f-41bf-aa82-07717b6d42b1.png)

But appears incorrectly on profile at  https://labyrinth.social/@tom

![CleanShot 2022-05-05 at 19 27 24](https://user-images.githubusercontent.com/11141120/167043796-875dc230-9717-49e0-b38a-712bf3327196.png)

This isn't local to my instance, Darius's pinned post is also missing this margin.  https://friend.camp/@darius

![CleanShot 2022-05-05 at 19 38 49](https://user-images.githubusercontent.com/11141120/167043888-79f97da6-887f-4f82-8c90-845bbd563ac6.png)

This issue doesn't seem to exist in Mastodon v3.4.6. For instance here is a status on my (now-defunct) profile on a Mastodon v3.4.6 server https://mastodon.cloud/@nowwearealltom

![CleanShot 2022-05-05 at 19 40 02](https://user-images.githubusercontent.com/11141120/167044021-7c66fccd-bcb1-4d9d-a195-96f94e9fb160.png)

I did a bit of digging to figure out what might be going on here and I noticed that the innermost div for these two different views have different classes.  

From https://labyrinth.social/web/accounts/108222192886738962:

![CleanShot 2022-05-05 at 19 42 33](https://user-images.githubusercontent.com/11141120/167044350-bd3133ba-a49c-40c4-8d8c-dea66fe34e16.png)

https://labyrinth.social/@tom

![CleanShot 2022-05-05 at 19 43 20](https://user-images.githubusercontent.com/11141120/167044346-2db9936e-b37b-4775-bd4b-1d8618fc949a.png)

Note `<div class="status__content__text status__content__text--visible translate">` vs  `<div class="e-content">`. I was thinking this might have something to do with the margin not being applied... however this distinction also exists in vanilla Mastodon but the margin gets applied regardless.

This is as far as my novice-level front end skills will carry me, I'm hopeless with sass. I'm hoping this helps pinpoint the issue in a way that can help someone else address it.

**Comment by dariusk** [comment]
Thank you for this! Investigating and will fix in the next Hometown release.

**Comment by dariusk** [comment]
This fix will be in the `v1.0.6+3.5.2` release.
