### ISSUE TITLE
New instance: digipres.club

### ISSUE THREAD

**Issue by mistydemeo** [hometown-fork/hometown#1166]
The Mastodon instance I run with @joshuatj is newly migrated to Hometown. Here's the information about it if you'd like to add it to the list of instances on the wiki.

Server: digipres.club
Description: digipres.club is a space for folks interested in productive conversations about digital preservation. If you enjoy talking about how to do memory work with computers, or even with cardboard boxes of old photos, you belong with us on digipres.club.
Accepting new users: Yes (with review)

**Comment by ghost** [comment]
@dariusk added it a few hours ago: https://github.com/hometown-fork/hometown/wiki/Hometown-servers/5a5adb7e98f03447119851de57ace17d8bc5f14f before I had the chance to do it. 😪

Closing! 😊
