### ISSUE TITLE
Emojis are in superscript?

### ISSUE THREAD

**Issue by biglifedecision** [hometown-fork/hometown#1167]
### Steps to reproduce the problem

Scroll posts on a timeline (global, local, home)

### Expected behaviour

emojis should show up in-line with text

### Actual behaviour

emojis appear to be too high? as though superscript?

### Specifications

3.5.2+1.0.5
Using a few different browsers/devices. 
Also tried using different themes (both Mastodon and Hometown themes)

Initially I thought maybe it was a local cache issue since upgrading Mastodon and migrating to Hometown earlier today (see https://github.com/hometown-fork/hometown/issues/1159). But after trying on different devices I do not think so. It could also be something from Mastodon, since upgrading from 3.4.6 -> 3.5.2 and before migrating to Hometown I did not happen to notice any emojis and how they appeared.

When looking at a post directly the emoji appears in line as expected.

**Comment by dariusk** [comment]
I fixed this since the code you merged during our earlier bug fixing session. It's in the v1.0.6 release today (you say above you're still on 1.0.5 or at least the sort of beta state you were in earlier).

**Comment by dariusk** [comment]
Seems from your announcement this was fixed so I'm closing the bug!
