### ISSUE TITLE
Remove "I don't like this" from new report UI

### ISSUE THREAD

**Issue by MaybeThisIsRu** [hometown-fork/hometown#1168]
### Pitch

The "I don't like this" selection doesn't do anything and is a dark pattern.

### Motivation

Mastodon/its forks are loved because moderation is human. Let's not take that out of it. Everyone benefits from removing this option, except for extra large instances like the flagship ones.

**Comment by lawremipsum** [comment]
We've taken the option out because, frankly, it is insulting and condescending, in addition to not doing anything but lecturing the user.

**Comment by ironiridis** [comment]
Looks like traction for this is happening in #1202

**Comment by dariusk** [comment]
Yes, thanks @MaybeThisIsRu -- I didn't catch this issue but it is indeed being tracked in #1202 so I'm closing this one.
