### ISSUE TITLE
Improve discoverability of multiple-choice poll interface

### ISSUE THREAD

**Issue by cincodenada** [hometown-fork/hometown#1174]
### Pitch

Firstly, if hometown isn't using the stock poll interface, my apologies, please ignore this - I'm not actually on an instance using Hometown, and I didn't want to spin up a whole instance to check, because from the code it seemed like the poll form was the same as upstream.

This is basically a duplicate [#10873](https://github.com/mastodon/mastodon/issues/10873) upstream, but so far it looks like the prospects on any movement there are not great. In sum, it should be clear when using the poll interface how to allow respondents to select multiple options. In the current interface, it is not apparent that you can even do that, much less how to. At the least, there should be a control that has some sort of label indicating that it affects the multiple choice-ness of a poll.

I think glitch-soc has [their own poll interface](https://github.com/glitch-soc/mastodon/blob/main/app/javascript/flavours/glitch/features/compose/components/poll_form.js) that seems more discoverable just from reading the code - I don't know what it actually looks like, but it might be worth seeing if you can just borrow theirs. I'm not sure if it is (or is based on) the previous Mastodon implementation or not, I don't remember what that looked like, but in any event it seems to have a dropdown that lets you choose between multiple-choice and not, which is much improved in my opinion.

And here are Pinafore and Tusky for reference, both of which also have well-labelled controls for changing this:
![pinaforepoll](https://user-images.githubusercontent.com/479715/172032638-122a29bb-79d5-41c1-9407-8aa7a0bb3dd3.png)
![tuskypoll](https://user-images.githubusercontent.com/479715/172032648-e467491d-76b0-4981-9559-a7fa90463f13.png)

### Motivation

Creating multiple-choice polls is a pretty basic function of any polling interface, I think, and right now it's hidden behind a UI that means most users won't even be aware it's an option, much less know how to enable it.

Improving the discoverability of this feature would benefit anyone who isn't good at guessing where the creator of Mastodon would hide features he considers "easter eggs", which is basically everyone who hasn't been poking around web interfaces extensively for a long time and/or isn't particularly technically inclined. I think everyone should have the same access to basic features as me, without having to be good at guessing how arcane interfaces work.

**Comment by dariusk** [comment]
Gosh, this reallllly ought to be fixed upstream but you're right that it's likely not going to see movement any time soon (and has not been addressed in v4). I'll see if I can fix it and make it an upstream PR first and foremost, I guess.

**Comment by dariusk** [comment]
Hey, check it out! The original toggle behavior works, too, still.

![image](https://user-images.githubusercontent.com/266454/205210006-d13152b5-7bbd-4861-9efe-8046e53d0bec.png)

**Comment by dariusk** [comment]
This is fixed in the upcoming v1.0.8 release.
