### ISSUE TITLE
pinned private replies shown as public

### ISSUE THREAD

**Issue by ghost** [hometown-fork/hometown#1178]
### Steps to reproduce the problem

1. make a public post
2. make a private reply and pin it
3. look at it in a private window and realize you can see the private post without logging in: ![image](https://user-images.githubusercontent.com/55312254/180669015-26c23473-a9c7-4ca4-83ad-d94989512fb2.png)
4. despair

### Expected behaviour

be unable to see the post unless logged in

### Actual behaviour

post is visible

### Specifications

v1.0.6+3.5.2

**Comment by ghost** [comment]
I can reproduce this on Hometown v1.0.6+3.5.2, but can't on Mastodon v3.5.3.

As it doesn't seems to be something that was happening on Mastodon at all, not present in any changelog (see v3.5.3: https://github.com/mastodon/mastodon/releases/tag/v3.5.3), it would likely be a bug introduced in Hometown modifications. 🫤

**Comment by Cassolotl** [comment]
I came here to report this, spotted on creacher.club, v1.0.5+3.5.2.

**Comment by johnholdun** [comment]
[Just submitted a PR that fixes this issue](https://github.com/hometown-fork/hometown/pull/1196). It looks like the filtering for local-only statuses managed to conflict with the filtering for private statuses.
