### ISSUE TITLE
write.as posts fail

### ISSUE THREAD

**Issue by hughrun** [hometown-fork/hometown#1182]
### Steps to reproduce the problem

1. follow write.as blog
2. new post published by blog author
3. blog post does not appear in Hometown server but does appear for a user following the blog from a non-Hometown Mastodon server

I'm _fairly_ sure Hometown is what is causing this, though I don't know enough about either the write.as codebase or the Mastodon codebase to be sure. I'm seeing an error in Sidekiq for this post, so it's received but my server can't render it:

```
NameError: uninitialized constant ActivityPub::Activity::Create::Formatter
```

### Expected behaviour

post should render in my feed

### Actual behaviour

post does not appear at al in feed

### Specifications

v1.0.6+3.5.2 on Ubuntu Linux

**Comment by dariusk** [comment]
Mooostly fixed in #1186, and #1183 is still open and I have a note there to fix the remaining bug where images aren't showing.
