### ISSUE TITLE
Option to exclude local-only posts from automatic post deletion

### ISSUE THREAD

**Issue by Stapper** [hometown-fork/hometown#1187]
Is it possible to add an exception for "local-only" posts in "Automated post deletion"?

**Comment by dariusk** [comment]
This is a good idea and I am tagging it for a future release.

**Comment by dariusk** [comment]
This is fixed in the upcoming v1.0.8 release.

**Comment by gnomon-** [comment]
Could the title of this ticket be updated to include the word "automatic"?

**Comment by dariusk** [comment]
@gnomon- sure
