### ISSUE TITLE
Can I search the fediverse?

### ISSUE THREAD

**Issue by jonbell-lot23** [hometown-fork/hometown#1188]
### Steps to reproduce the problem

1. I typed something in the search
2. I expected to see it search the fediverse, or give me an option to filter to it
3. Couldn't make it work

I can't tell if this is by design, or if I'm doing something wrong.

### Expected behaviour

Search results from the fediverse

### Actual behaviour

Search results only from my local instance

### Specifications

Latest version of Hometown as of today

**Comment by ghost** [comment]
Hello,

You **can't** search the fediverse and it's on purpose.

You **can** however search for public posts that contain hashtags. If that's not working on the instance you're on, you may have to wait a bit if the server has just been set up (it takes a bit of time for the server to discover & digest all this federated data) or there might be a federation issue with your server.

If you added full-text search with Elasticsearch you are also able to search from your own posts content.

Don't hesitate to check out the Mastodon documentation to know more about all this: https://docs.joinmastodon.org

Hope this helps.

**Comment by dariusk** [comment]
Thanks @mthld. Yes, the lack of general search capability is by design in Mastodon (and also made very very hard to do on fediverse in general due to its structure). And I think on the balance it's a very good thing, though it takes some getting used to.

**Comment by jonbell-lot23** [comment]
Thanks, gang!
