### ISSUE TITLE
Option to post to followers + local

### ISSUE THREAD

**Issue by Ragzouken** [hometown-fork/hometown#1190]
### Pitch

Post visibility option that posts to follower timelines, local timeline, but not federated timeline.

### Motivation

I've seen some sentiment towards posting unlisted by default, avoiding every little post going to federated. However this also takes things off of the local timeline where, personally, I would like to see every little post (we're a private ~25 person instance).

I don't think there's any way to do this at the moment. It would also probably work for me if I could set up a column that my home timeline filtered down to just local users (i.e local posts + all visibilities of posts of local users i follow), but I don't think this is possible either?

**Comment by dariusk** [comment]
Sorry, this is probably out of scope for what I can do on Hometown. I'll leave this open for the next week or so when I have significant time set aside to work on this project but... expect me to close it.
