### ISSUE TITLE
Recent german locale config changes break docker build

### ISSUE THREAD

**Issue by jimfingal** [hometown-fork/hometown#1192]
### Steps to reproduce the problem

1. Run `docker-compose build` on fresh checkout

### Expected behaviour

Build succeeds

### Actual behaviour

Docker build fails with `#0 272.4 I18n::InvalidLocaleData: can not load translations from /opt/mastodon/config/locales/de.yml: #<Psych::SyntaxError: (/opt/mastodon/config/locales/de.yml): found character that cannot start any token while scanning for the next token at line 5 column 26>`

### Specifications

Found in current `hometown-dev` branch, commit: 8527f019870a27dff5b41e7ef81042035279c564

Resetting to 7e9c05cf5d2b165e8be5339b0a6bd5f5f59ce8ab and running `docker-compose build` results in a successful build.

**Comment by johnholdun** [comment]
I saw this problem as well trying to run locally (i.e. without Docker). #1179 seems to fix it for me.

**Comment by dariusk** [comment]
Complete fix is now in `hometown-dev` and can be cherry-picked from 3f2b00542b43d897a58d3685016d7247834fca64!
