### ISSUE TITLE
No documentation on fresh installs

### ISSUE THREAD

**Issue by jtracey** [hometown-fork/hometown#1197]
The current documentation doesn't seem to clearly state anywhere what you're supposed to do for fresh production installs. I.e., is it sufficient to follow the normal Mastodon "install from source" process (but pointed at this git repo), or is it required/recommended to perform an install of upstream Mastodon first, then apply the patch set and DB migrations?

**Comment by kimadactyl** [comment]
I'd also like to see this if poss!

**Comment by dariusk** [comment]
The [initial migration](https://github.com/hometown-fork/hometown/wiki/Initial-migration) wiki page says to make sure you have the correct version of Mastodon already installed before moving ahead. I've clarified the wording a bit so it now reads:

> Hello! This is a guide to help you migrate from Mastodon to Hometown. This guide shows you how to migrate from Mastodon 3.5.5 to Hometown v1.0.7+3.5.5. Right now we are up to date with Mastodon 3.5.5, so __make sure you are running Mastodon 3.5.5 before trying this__. There are [Mastodon installation instructions here](https://docs.joinmastodon.org/user/run-your-own/). And please test in a local development environment or a test server first if at all possible.

**Comment by dariusk** [comment]
So yes the intent is to run upstream first, then migrate. I have never tested Hometown "from scratch" though there is no reason to assume it wouldn't work. But also it is way way easier to make sure that your Mastodon instance works _first_, then if upgrading to Hometown breaks something we know it's an issue with Hometown somehow (rather than a Mastodon problem).

**Comment by jtracey** [comment]
At least to my reading, I think I'd still be confused, since that's a migration guide and not an installation guide (the second sentence in that paragraph isn't "This is a guide to help you get Hometown running."). I'd prefer if the content of your comment were documented somewhere there, i.e., that only migrations, and not fresh installations, are supported. At least now a search can turn up this issue, so not the end of the world regardless.

(FWIW, I installed without migrating, and it seems to have worked fine, but if that path isn't tested then yeah probably not a good idea in general.)

Thanks!
