### ISSUE TITLE
Allow import/export of instance-level domain blocks/allows

### ISSUE THREAD

**Issue by samuk** [hometown-fork/hometown#1199]
### Pitch

Adds an export button to the moderator federation page and an import block to the moderator add new domain block/allow page.
Blocked domains are exported along with the severity level.

On import, already-blocked domains will not be modified (e.g. a currently-silenced domain will not be upgraded to suspended).

### Motivation

A number of admins have expressed that they would like this feature https://github.com/mastodon/mastodon/pull/15664#issuecomment-843180314

The code already exists. If the author makes a pull here is it likely to be accepted?

**Comment by dariusk** [comment]
This feature has now been merged into Mastodon! As of a few hours ago. https://github.com/mastodon/mastodon/pull/20597

So it will appear in a future Hometown version, whenever the next Mastodon release containing that change happens.
