### ISSUE TITLE
Wrong versions in wiki page "Initial migration"

### ISSUE THREAD

**Issue by rebeka-catalina** [hometown-fork/hometown#1200]
### Steps to reproduce the problem

The version in 2nd and 3rd code block [Initial migration](https://github.com/hometown-fork/hometown/wiki/Initial-migration) says to `git branch` and  `git checkout` to version hometown-v1.0.7+3.5.4 and to `git merge` hometown-v1.0.7+3.5.4.

(Using hometown-v1.0.7+3.5.4 instead made everything work as expected)

### Expected behaviour

The described process should bring my mastodon server to hometown - i.e.: git merge should work.

### Actual behaviour

I had git merge conflicts

### Specifications

Mastodon 3.5.5

**Comment by dariusk** [comment]
Thank you, fixed!
