### ISSUE TITLE
Change the mastodon references to hometown

### ISSUE THREAD

**Issue by Huy-Ngo** [hometown-fork/hometown#1206]
### Pitch

Currently, the links in footers all refer to Mastodon documentation and source code. I think these should be changed to those of hometown instead.

### Motivation

I think this would help potential contributors to know where to contribute code easier. It would also be less confusing and misleading, given that now the link for "Source code" doesn't actually lead to the source code the hometown instances are running on.

**Comment by Huy-Ngo** [comment]
Case in point I just mistakenly opened this issue [on the wrong repo](https://github.com/mastodon/mastodon/issues/21175) :weary:

**Comment by dariusk** [comment]
Ah -- I link both code repositories but it is worded in a weird and confusing way. I will fix that! Also I will change the "Documentation" link to point to the Hometown wiki, and from there have a link to the Mastodon docs to cover Mastodon-specific features. Thank you!

**Comment by dariusk** [comment]
This is fixed in the upcoming v1.0.8 release.
