### ISSUE TITLE
Wiki documentation should be updated to point to v1.0.7 installation/update instructions

### ISSUE THREAD

**Issue by krusynth** [hometown-fork/hometown#1208]
### Steps to reproduce the problem

1. Go to the [Hometown wiki home page](https://github.com/hometown-fork/hometown/wiki)
2. The first link points to [Hometown v1.0.5](https://github.com/hometown-fork/hometown/releases/v1.0.5%2B3.3.0) not [Hometown v1.0.7](https://github.com/hometown-fork/hometown/releases/tag/v1.0.7%2B3.5.5)

Sorry Darius, I would have done a PR but apparently you can't do PRs against the wiki? 🤔  

Anyway, this bug is more properly titled "don't let Bill do sysadmin tasks like upgrading software late on a Sunday night because he will read the wrong, outdated instructions and scare the heck out of himself for about an hour until he realizes he accidentally downgraded instead of upgrading." 😅

Thanks!!!

### Expected behaviour

The wiki should point to v1.0.7

### Actual behaviour

The wiki points to v1.0.5

### Specifications

N/A

**Comment by dariusk** [comment]
Thank you, fixed!

**Comment by dariusk** [comment]
Sorry for the scare!
