### ISSUE TITLE
Consider applying UI patch to revert timestamp link behavior to v3

### ISSUE THREAD

**Issue by dariusk** [hometown-fork/hometown#1214]
Consider applying this UI patch to v4: https://commit.pup.cloud/maff/queer.party/src/branch/master/patches/4.0.0_4-revert-captive-links.patch

It makes it so that username links and timestamps in posts go to the server of origin rather than a local server proxy (reverts back to the v3 behavior).

**Comment by graue** [comment]
Just to share one person's experience: when I was new to Mastodon a few months ago, I initially found it frustrating and confusing that if I opened any link in a new tab, it would open on the original server where I couldn't interact with the post. I wanted all Mastodon links to stay within my own instance so I could interact. In other words, as a new user, I wanted the v4 behavior.

Now that I'm used to the v3 behavior, I understand the desire for it too: to see fave counts, to see a complete set of replies, or to get a more up-to-date view of someone's profile. The last one is the most common reason I do it, especially when reviewing follow requests. So I'm not going to make a strong case for either the v3 or v4 behavior.

That being said, in an ideal world, I think we would want the v4 behavior, plus built-in functionality to backfill recent posts when viewing someone's profile, etc., right? Like, ideally, it shouldn't be necessary to go to the original server to make sure you're getting an up-to-date and complete view. I wonder if there's any effort underway to fix that underlying problem, so we wouldn't have to use this workaround that confuses new users (at least in my case).

**Comment by wakest** [comment]
@graue you explained the situation perfectly, sadly its really either an either or situation as the very foundation of how mastodon is designed is why we are having this issue. It doesnt seem like a solution to this issues has even peen properly proposed to mastodon or really any of the fediverse that I can tell. So in the short to medium term we just have to choose v3 or v4 behavior. In the long term I think maybe posts could be streamed in from the remote server one at a time to backfill but this would me a major rethinking of how posts move around the network.

**Comment by dariusk** [comment]
Relevant patch here

https://queer.party/@maffsie/109421858142013005

**Comment by paeneultima** [comment]
I would love to see the v3 functionality carried forward!

**Comment by dariusk** [comment]
See also comments here that didn't make it to github: https://friend.camp/@darius/109538006755061781

**Comment by dariusk** [comment]
Strongly considering this suggestion from @maybethisisru :

> Timestamp = original. Almost a convention on the web at this point. For profiles, keep new v4 behaviour. Although I’ve gotten used to clicking the profile image, that was always a work around and not “correct”  behaviour.

**Comment by lawremipsum** [comment]
I support reverting to v3. Making it harder to get to the remote profile/post is a net negative. We want people to click through to do things like read all the replies.

**Comment by nevillepark** [comment]
I also support reverting to the v3 behaviour. It's very irritating to have to jump through hoops to get the canonical URL on Mastodon 4.0 sites.
