### ISSUE TITLE
why is this not a PR on mastodon?

### ISSUE THREAD

**Issue by pvinis** [hometown-fork/hometown#1215]
### Steps to reproduce the problem

I read the readme and didn't find any reasoning for this fork. since it's "99.999%" mastodon, why not just make it a PR? 
could you add some reading to the readme?
thanks. 

### Expected behaviour

reasoning to exist on readme

### Actual behaviour

doesn't exist

### Specifications

.

**Comment by leeomara** [comment]
I believe this is in the readme:

> By our best understanding, our major changes are not wanted by the Mastodon project, hence maintaining this fork instead of trying to commit the changes to Mastodon.

See also this previous issue #46.

**Comment by dariusk** [comment]
Closing this since we do have this in the README. @pvinis, let me know if I'm missing something here.

**Comment by pvinis** [comment]
oh? where? I missed it 🤔. sure close it. but it would be helpful to have that info front and center.

**Comment by dariusk** [comment]
It's in the third paragraph of the README. The same one you quoted with the "99.999% similar" line

**Comment by pvinis** [comment]
> By our best understanding, our major changes are not wanted by the Mastodon project, hence maintaining this fork instead of trying to commit the changes to Mastodon.

gotcha. thanks.
