### ISSUE TITLE
Expand the documentation for exclusive lists to further explain functionality

### ISSUE THREAD

**Issue by thomasmdickinson** [hometown-fork/hometown#1216]
### Pitch

I suggest that the docs should include additional description of the exclusive lists functionality, clarifying that:

- You can add yourself to an exclusive list, and your posts will be visible in the lists, but doing so does not remove yourself from your Home timeline (Not sure if this is intended behavior or a bug, but this is the current functionality)
- The same account can be on any number of exclusive or non-exclusive lists. 
- If someone is on an exclusive list, this excludes them from the Home timeline, but _not_ from other lists, or the Local or Federated timelines, or search results

There may be other nuances and edge cases that are worth explaining but these are the ones that came up with a friend today so I thought I'd share them as areas for improvement in the docs.

### Motivation

Of course Hometown users can just play around and find out for themselves, but additional description would be helpful especially for users not already on a Hometown server yet but investigating the utility of the feature to decide whether to switch to a Hometown server.

**Comment by dariusk** [comment]
Thanks @thomasmdickinson -- I put what you wrote mostly verbatim on the wiki:

https://github.com/hometown-fork/hometown/wiki/Exclusive-lists
