### ISSUE TITLE
User preference setting to disable RSS

### ISSUE THREAD

**Issue by lawremipsum** [hometown-fork/hometown#1232]
### Pitch

More than one MSP Social user has said that their public post availability in RSS discourages them from otherwise posting publicly.

Users should be able to toggle whether their feed is available via RSS.

A good place for this would be the Preferences -> Other menu, alongside similar privacy settings.

### Motivation

RSS syndication is a leaky default in the current environment; HTML scraping requires more effort/technical ability.

Because RSS feed subscription is trivial, avoids expected follow-approval behavior, and is integrated into some fediverse software as a "feature," allowing users to disable RSS would meaningfully impair casual block evasion.

Every user who uses "approve followers" could benefit because it brings the server's publishing behavior more in line with their expectations.

**Comment by ghost** [comment]
Although I am a somewhat vociferous user of RSS, I think this suggestion makes sense. Such an enhancement would align technically-oriented implementation with casual user expectation, and that's a good thing IMO. Even if I wouldn't personally use it.

**Comment by ironiridis** [comment]
I'd like to see an administrative option to default this setting to "off" for new users, too, if an instance is privacy-minded. There are a lot of scenarios I could imagine where having safe and private defaults would be a big win.

**Comment by dariusk** [comment]
Done! This will be in the 1.0.8 release. See #1233 for details. I made it work exactly like the search engine indexing opt-out.
