### ISSUE TITLE
Update search engine opt-out language in preferences

### ISSUE THREAD

**Issue by dariusk** [hometown-fork/hometown#1234]
Search engine opt-out doesn't exactly opt all your posts out of being indexed. For example, if you reply to a post of a Mastodon or Hometown user (and probably any other federated software user) and _their_ content is indexed by search engines, your reply post will be indexed on _their_ end whether you like it or not. The model here, intentional or not, is that the originator of a thread kind of "owns" whether things are indexed, at least as they are rendered on their canonical version of the content that was posted to their server.

Long thread about this here: https://friend.camp/@darius/109457118882321074

For now I am at least going to update the language on the opt-out to be clearer that it is only _some_ content that is opted out of indexing, and that when you reply publicly to anyone (even if unlisted, even if you check the opt-out box in your settings) your reply might be indexed.

**Comment by dariusk** [comment]
For further reference see this Mastodon issue, https://github.com/mastodon/mastodon/issues/22047

**Comment by skopf** [comment]
@dariusk Unfortunately, this is not sufficient.

There are more situations in which toots will end up in a search engine like Google, for example
- if the toot contains a tag, it will be displayed on the tag page as well
- if the profile has at least one follower on a remote instance, it will show up on the federated timeline of the remote instance
- if someone boosts a post, all of the above applies to the profile who boosted the post

Toots are simply displayed on too many pages to be able to hold up with the promise that they do not end up in Google. Hence I would suggest to completely drop this option as it gives a false sense of privacy.

I described this specific problem together with other privacy concerns here:
https://medium.com/@s.kopf/mastodon-is-a-zero-privacy-network-here-is-what-you-need-to-know-86aeed685e41

**Comment by dariusk** [comment]
`noindex` on a profile page is also increasingly being used by third-party tools as a signifier that the user does not consent to having their data collected for search indexing purposes. I do think it does *something* and so I am not inclined to remove it entirely. Maybe we need to be even more clear about what it does or does not do. I would still like this to be an option for people who want it (as many people do).
