### ISSUE TITLE
Allow customizing the length of registration "why do you want to join?" field

### ISSUE THREAD

**Issue by Briar503** [hometown-fork/hometown#1236]
### Pitch

Currently the "Why do you want to join?" field that appears  on the main page when approvals are required for registration has a max character limit of 420 characters. 

### Motivation

This length is prohibitive if you request specific details from those seeking to register. For example, we ask for users to list who they know on the instance, how they want to contribute, and geographic location information.

Perhaps this could be added as an environment configuration similar to length of toot.

**Comment by dariusk** [comment]
Oh weird that it's limited so much. I'll probably just increase it to 5k characters and not bother with customization.

**Comment by nileshtrivedi** [comment]
It seems to be [defined in a single place](https://github.com/hometown-fork/hometown/blame/hometown-dev/app/models/user_invite_request.rb#L16) and I couldn't find any discussion on justifying this particular length limit [in the original commit or issue](https://github.com/mastodon/mastodon/pull/10524).

**Comment by dariusk** [comment]
@nileshtrivedi (this is closed but I "assigned" it to you to keep track for release notes of who fixed it)
