### ISSUE TITLE
No margin between paragraphs in reply interface

### ISSUE THREAD

**Issue by thomasmdickinson** [hometown-fork/hometown#1241]
### Steps to reproduce the problem

1. On desktop, open any toot with multiple paragraphs (for example this one https://friend.camp/@darius/102368208532424821) 
2. Click reply to see reply interface

![toot reply interface, paragraphs do not have margins](https://user-images.githubusercontent.com/11141120/206803561-fc896f21-ca18-4853-b1a0-768375b2e57f.png)

### Expected behaviour

There should be some margin between paragraphs

### Actual behaviour

There is no margin

### Detailed description

As a workaround, I have used this custom css to add the margin.

`/* add missing margin in reply interface */`
`.reply-indicator__content p, .status__content p {`
`  margin-bottom: 20px;`
`}`

Not sure whether this is an issue on all hometown servers, or just a weird compilation error on mine, but thought I'd document the issue just in case.

### Specifications

v3.5.5+hometown-1.0.8
safari for MacOS Version 16.1

**Comment by dariusk** [comment]
I can reproduce. I'll fix it in the next release.
