### ISSUE TITLE
Low contrast: boost state hard to read in Macaron (Pastel Light) theme

### ISSUE THREAD

**Issue by graue** [hometown-fork/hometown#1243]
### Steps to reproduce the problem

1. Switch to the Macaron (Pastel Light) theme
2. Boost a toot
3. Look at the color of the boost icon

### Expected behaviour

It's possible to visually distinguish whether I boosted a toot or not

### Actual behaviour

The colors are too close together to easily tell

### Detailed description

I love this colorful theme, but the change in color of the boost icon from gray to slightly bluish gray is barely perceptible. I can't tell if I've boosted a toot and keep unboosting things I meant to boost.

Unboosted state:
![macaron-unboosted](https://user-images.githubusercontent.com/1730853/206927899-8056ffe5-983e-4f98-a0cc-52c13bbeccbe.png)

Boosted state:
![macaron-boosted](https://user-images.githubusercontent.com/1730853/206927907-5630b3fd-aeb3-4a69-8dc3-434102856e8a.png)

### Specifications

Hometown v1.0.7+3.5.5
Firefox 107 on a Dell laptop

**Comment by dariusk** [comment]
Planning to change it to this on-theme color:
![image](https://user-images.githubusercontent.com/266454/207186539-4d2ac943-da57-4ae7-a97d-6e426d533394.png)

**Comment by graue** [comment]
Thank you!
