### ISSUE TITLE
Remove "Filtered" notifications in feed

### ISSUE THREAD

**Issue by Monque27** [hometown-fork/hometown#1245]
### Pitch

I would like to see the removal of the "Filtered" notification in the feed. 

I have two suggestions:
1. Turn off the notification all together
2. Make it available with a toggle, but make it more informative (e.g. "Filtered via text filter for 'Elon'")

### Motivation

I can't see the point of it - there is no information (such as which filter is active) and nothing to click on if you want to peek at the filtered content. It just takes up screen real estate.

My reason for filtering stuff is mainly that I don't want to see it - but in the case illustrated in the attached pic, it's taking up most of the view.

<img width="565" alt="CleanShot 2022-12-15 at 11 14 49" src="https://user-images.githubusercontent.com/61249900/207915841-474e7aa3-8136-4911-bffa-522f4cfba2b5.png">

**Comment by dariusk** [comment]
You can already do this -- select "Drop instead of hide" when you create a filter. It'll be like the content was never there.

**Comment by Monque27** [comment]
...And there it is. Thanks!
