### ISSUE TITLE
Empty space in desktop view whilte using RTL language as interface language

### ISSUE THREAD

**Issue by eyalSci** [hometown-fork/hometown#1268]
### Steps to reproduce the problem

1. Change interface language to Hebrew
2. Look at desktop using advanced web view

### Expected behaviour

Posts started with only a small gap between their beginning (right) to the right bar

### Actual behaviour

There is a major gap between the bar and the beginning of the post

### Detailed description

It could be connected to #1267 
Also, notifications about new follows act as it should, but this problem also affects notifications about faves.

![image](https://user-images.githubusercontent.com/8685770/210572417-eb95dfe0-c4cc-4478-97d0-b7ec3d8ce0ac.png)

![image](https://user-images.githubusercontent.com/8685770/210573330-2dfe1631-dcf5-4104-8232-1d46195e87ca.png)

### Specifications

Hometown: v4.0.2+hometown-1.1.0
Firefox on windows 10

**Comment by dariusk** [comment]
@eyal6699 This appears to be a Mastodon bug. You can see below a screenshot from mastodon.social set to Hebrew and this problem occurs.

![image](https://user-images.githubusercontent.com/266454/210888178-49ac1e84-bae3-4b59-8870-110ecbd5344e.png)

I will open a bug report over there.

**Comment by dariusk** [comment]
@eyal6699 I have opened a bug report here: https://github.com/mastodon/mastodon/issues/20862

If it is not fixed by the time of the next Hometown release, I will make a fix myself.

**Comment by dariusk** [comment]
@eyal6699 This has been fixed in Mastodon, so will be fixed the next time Mastodon does a release and Hometown updates to it!

https://github.com/mastodon/mastodon/pull/23157
