### ISSUE TITLE
Restore 3.x username suggestion behavior

### ISSUE THREAD

**Issue by a-dows** [hometown-fork/hometown#1272]
### Pitch

Since updating to v4.0.2+hometown-1.1.0, the web interface's suggested usernames to tag in a post (shown when typing the @ character and waiting) appear to weight follower count, rather than followers/accounts you follow first.

The original sorting should be restored.

### Motivation

Accounts you follow are far more likely to be tagged or interacted in a new post than a random high-follower-count account.

**Comment by dariusk** [comment]
Mostly a note for future me, there is more discussion here

https://friend.camp/@darius/109638046110736281

**Comment by dariusk** [comment]
~Looks like I need to revert this change: https://github.com/mastodon/mastodon/pull/19251~ 

Nope, I just needed to add a ranking order based on following

**Comment by dariusk** [comment]
Also made a PR on Mastodon https://github.com/mastodon/mastodon/pull/22956

**Comment by dariusk** [comment]
For the record, after consulting with Eugen, we came up with a better fix: 15e78b9a0a791c90c8c49b7ae4cce3d698e52143
