### ISSUE TITLE
adding the the MAX_TOOT_CHARS line to .env.production only updates the web interface.

### ISSUE THREAD

**Issue by stickbear2015** [hometown-fork/hometown#1273]
Hello,
In the article on the wiki
[Custom max toot characters](https://github.com/hometown-fork/hometown/wiki/Custom-max-toot-characters)
it says:

> You'll need to add the following lines in your .env.production file:
MAX_TOOT_CHARS=500
Just replace 500 by the limit you want and recompile the assets:

but when I do this, I only see the change reflected in the web interface, and not inside apps that I connect to my instance.
I decided to do a little more research and ran across
[this article](https://www.draklyckan.se/2021/11/how-to-increase-the-character-limit-for-toots-in-mastodon/)
but looking through the information on it, the modifications they suggest either don't apply or the files are significantly different from the information they indicate.
Have I missed something? Or am I referencing out of date information.
Thanks.

**Comment by amacleod457** [comment]
Seeing the same issue here.
Web interface allows 2,000 character limit, but API apps are given a 500 character limit.

Other known Hometown instances successfully showing character limits greater than 500, typically 2,000.
What are we missing? Did something change with this since the Mastodon 4 upgrade?

**Comment by johnholdun** [comment]
Did you also restart your Hometown server (the final step on that page of the wiki)? If you're seeing changes on the frontend and not the backend, it suggests to me that that's the solution.

**Comment by stickbear2015** [comment]
Hello,
> systemctl restart mastodon-sidekiq mastodon-streaming mastodon-web

was executed and just for amusement sake, the entire server was restarted.
Their was no change in what clients are seing for toot (post) length.
But the web shows 2000 as the length.

**Comment by dariusk** [comment]
@stickbear2015 What applications are your users reporting this in? My suspicion is that the API responding just fine and your users are using an app that just assumes 500 characters without checking the `max_characters` advertised by the server at, for example, https://friend.camp/api/v1/instance/

**Comment by amacleod457** [comment]
Hi folks,
We very much appreciate the quick support here.
It does seem that our API client Tweesecake, is assuming the 500 character limit and not checking with the server.
When adapted to our server, the  API url provided does show 2000 characters.

We will follow up this issue directly with the developers of the app.

Thanks again. Will be closing this issue.
