### ISSUE TITLE
New Instance: giantheart.social

### ISSUE THREAD

**Issue by rainbow-bamboo** [hometown-fork/hometown#1308]
### Pitch

I'm starting a community for poets and I would love to be included in the directory.

### Motivation

Name: giantheart.social

Description: A safe space to share your poems and the stories behind them. 
We're based in the Caribbean, have a little radio station, and a 5000 character limit so that you can post longer poems.

Accepting new users?: yes (by invite)

**Comment by ghost** [comment]
Hello!

Welcome to Hometown! I've added your instance to [the wiki](https://github.com/hometown-fork/hometown/wiki/Hometown-servers).
