### ISSUE TITLE
Update to Mastodon 4.1 to enable Block List Imports

### ISSUE THREAD

**Issue by Crazypedia** [hometown-fork/hometown#1311]
### Pitch

Update the base version of Mastodon in hometown to 4.1 to support Block List Importing. 

### Motivation

Moderation at scale has always been an issue with the core Mastodon servers, and now we have external tools to generate and curate lists of known bad actors amongst fellow admins. In order to take advantage of this however, we need the ability to import those lists.

**Comment by rscmbbng** [comment]
This was added in v1.10 already by backporting unreleased features of mastodon:
https://github.com/hometown-fork/hometown/releases/tag/v4.0.2%2Bhometown-1.1.0#New%20features
