### ISSUE TITLE
Please cherry-pick upstream PR for Load More fix

### ISSUE THREAD

**Issue by ironiridis** [hometown-fork/hometown#1313]
### Pitch

We have a user on our instance who routinely hits an upstream bug where turning off the "show boosts" toggle in a timeline, and then encountering a full page of boosts while loading, causes the timeline to never load any more content after that. Upstream has [a PR](https://github.com/mastodon/mastodon/pull/24930) that addresses this, at least in part. It would be lovely if this could be cherry-picked if upstream isn't releasing it in time for the next Hometown release.

### Motivation

This would resolve an issue that is encountered by one of our users on a regular basis.

**Comment by pronoiac** [comment]
The PR mentioned is included in #1337 , though I don't know how long the draft or review will take.

**Comment by ironiridis** [comment]
I'm assuming this was pulled in as part of v4.2.10+hometown-1.1.1 . Closing for now.
