### ISSUE TITLE
Allow editing alt text / media descriptions when editing saved posts

### ISSUE THREAD

**Issue by pronoiac** [hometown-fork/hometown#1330]
### Pitch

We should let people correct and edit alt text. 

[The PR for this was merged into Mastodon v4.1.](https://github.com/mastodon/mastodon/pull/20878)

Workaround: delete the media, re-add it, then add alt text.

### Motivation

This would remove some friction, and some confusion; Ivory, for example, lets you edit it, but it won't save.

**Comment by webbongithub** [comment]
(Disclaimer: I am the author of 8bloat)

[8bloat](https://git.sr.ht/~webb/8bloat) depends on this to add alt text to posts, which is used by a nonzero amount of people. It's also an important accessibility feature. Often, people will reply with alt text or descriptions which you can edit in to the original post. It really stings not being able to do that.

**Comment by hartsick** [comment]
@pronoiac hi! it seems like this was included in the latest release of hometown. want to confirm and close if so?

**Comment by pronoiac** [comment]
@hartsick I confirmed I can edit and save media descriptions from Ivory and the web interface! (It looks like descriptions aren't displaying well right now in the web interface, but that's a separate, upstream, issue.) Closing issue.
