### ISSUE TITLE
Question: timeframe for next release?

### ISSUE THREAD

**Issue by rscmbbng** [hometown-fork/hometown#1336]
### Pitch

> Also, the Mastodon team will no longer provide security updates for version 4.0.x after 2023-10-31. The next release of Hometown will happen before then and will bump us up to version 4.2.x.

Hi Darius and other contributors,

first apologies for mis-using the feature request form. Hometown's Mastodon code base is currently no longer seeing security updates.  When can we expect the bump to 4.2.x and what can we do to help (aside from submitting a PR, as I don't personally have the skills for that)?

### Motivation

Being on an older branch is not such a big deal, but the ability to rapidly install security updates is important. Switching to the 4.2.x branch already means it is quicker to integrate future security patches. 

many thanks!

**Comment by pronoiac** [comment]
There's a PR open - #1337 - to update to Mastodon v4.2. I don't know how long the draft or review will take. I believe if there were a security issue, that it would be backported quickly.

**Comment by tillkruss** [comment]
https://friend.camp/@darius/111543227582773608
