### ISSUE TITLE
Incorrect upgrade instructions on latest release?

### ISSUE THREAD

**Issue by yaxu** [hometown-fork/hometown#1345]
https://github.com/hometown-fork/hometown/releases/tag/v4.0.15%2Bhometown-1.1.1

I think this:
```
git remote update && git checkout v4.0.14+hometown-1.1.1
```
should be this:
```
git remote update && git checkout v4.0.15+hometown-1.1.1
```

Meaning people think they've upgraded when they haven't.

**Comment by yaxu** [comment]
Has someone just fixed this or am I losing my mind? :)

**Comment by rscmbbng** [comment]
> These are instructions for upgrading from `Hometown v4.0.14+1.1.1`

It still says this, so I think someone changed it while you reported it..
