### ISSUE TITLE
Mistake in initial migration wiki documentation

### ISSUE THREAD

**Issue by rscmbbng** [hometown-fork/hometown#21]
The step  `git pull hometown hometown-v1.0.1+2.9.2` fails because it points to a branch that doesn't currently exist. Going by the existing branches in this repo it should be `git pull hometown hometown-v1.0.0+2.9.3`.

**Comment by dariusk** [comment]
Thanks, I've corrected it. I forgot that since I'm using tags for releases the process is a bit different. The new procedure is:

```bash
git remote add hometown git@github.com:hometown-fork/mastodon.git
git branch hometown-v1.0.1+2.9.3
git checkout hometown-v1.0.1+2.9.3

git fetch --tags
git merge v1.0.1+2.9.3
```
