### ISSUE TITLE
Missing step in version upgrade instructions

### ISSUE THREAD

**Issue by rscmbbng** [hometown-fork/hometown#33]
While following the [v1.0.3 release instructions](https://github.com/hometown-fork/hometown/releases/v1.0.3%2B3.0.1) on `git fetch && git checkout v1.0.3+3.0.1` the following occurs:

`error: pathspec 'v1.0.3+3.0.1' did not match any file(s) known to git.`

That happens when people have multiple remotes (as would be the case when having migrated from vanilla masto as per the instructions on the wiki).

The solution is to update the remotes first:
`git remote update`

**Comment by dariusk** [comment]
Thank you, fixed.
