### ISSUE TITLE
Can't merge Hometown tags

### ISSUE THREAD

**Issue by marcelmouse** [hometown-fork/hometown#34]
Hello,

I tried to find search around for some answers on this but it seems I might be missing something. When I run `git merge v1.0.1+2.9.3` an error is returned. It looks like git fetch --tags is pulling the tags from mastodon not hometown. Is this correct? Any guidance is appreciated!

Thanks.

Pasting terminal commands and responses below:

`mastodon@localhost:~/live$ git status`
On branch hometown-v1.0.1+2.9.3
nothing to commit, working tree clean

`mastodon@localhost:~/live$ git fetch --tags`

`mastodon@localhost:~/live$ git merge v1.0.1+2.9.3`
merge: v1.0.1+2.9.3 - not something we can merge

`mastodon@localhost:~/live$ git describe --tags`
v2.9.3

`mastodon@localhost:~/live$ git remote`
hometown
origin

**Comment by davefp** [comment]
I believe that because you have multiple remotes you need to specify `hometown` when you do your fetch: `git fetch hometown --tags`.

After you run that the relevant hometown tag should appear when you run `git tag`.

**Comment by marcelmouse** [comment]
Thank you! Didn't quite succeed as I got a bunch of merge conflicts but your comment was helpful!
