### ISSUE TITLE
Instances list

### ISSUE THREAD

**Issue by stemy2** [hometown-fork/hometown#41]
### Pitch

You should create an official site with a list of available hometown instances (or at least indicate it in your github page).

### Motivation

It would be more practical than browsing countless pages in search engines to maybe find an instance among results.

**Comment by ghost** [comment]
Hi,

There is already a wiki entry regarding running Hometown instances: https://github.com/hometown-fork/hometown/wiki/Hometown-servers but we could indeed link it in the README.md file

Would it fix the issue?

**Comment by stemy2** [comment]
Good idea, it would be easier to find.
