### ISSUE TITLE
Pinning a status stops it from being local-only

### ISSUE THREAD

**Issue by a-dows** [hometown-fork/hometown#42]
### Expected behaviour

A local-only post set to public remains local-only when pinned to the user's profile.

### Actual behaviour

All public posts, local-only or federated, appear on a user's profile when pinned, even to logged-out viewers.

### Steps to reproduce the problem

Posted a local-only public status. Pinned status to profile. Visited profile in private browser window, saw status.

**Comment by a-dows** [comment]
For context: I wanted to pin the invite to my instance's Discord on my profile, but make it visible only to logged in users of the instance. When I pinned the post, it ceased to be local-only.

**Comment by dariusk** [comment]
Fixed in the 1.0.4 release! Sorry about the delay.
