### ISSUE TITLE
Upstream the changes

### ISSUE THREAD

**Issue by davidak** [hometown-fork/hometown#46]
### Pitch

This is the obvious question: Have you considered to upstreaming your changes to Mastodon?

Have you already tried it? What is the status?

### Motivation

I'm curious why a fork is needed. README is lacking this information. Please add it :)

**Comment by dariusk** [comment]
Hi! My understanding is that local-only posting is not a feature that upstream wants, mostly based on this pull request that has been continuously updated but never merged (or even seriously discussed) for a few years now:

https://github.com/tootsuite/mastodon/pull/8427

**Comment by davidak** [comment]
The first 2 sentences from the comment from Gargron states clearly:

>I think it introduces very real centralization dynamics into the software. Our selling point is "pick whatever server you like, you can talk to your friends from anywhere". 

That's a good reason against it.

So you can add to the Readme that this project implements a feature that upstream don't want. That is a good reason for a fork!

When this was considered and decided for or against it, this issue can get closed.

**Comment by dariusk** [comment]
Oh I think I misunderstood your original request. I will happily add rationale to the docs.
