### ISSUE TITLE
Statuses posted from third-party clients federate even when "Allow my posts to reach other instances by default" is disabled

### ISSUE THREAD

**Issue by lostfictions** [hometown-fork/hometown#48]
In my preferences "Allow my posts to reach other instances by default" (default federation) is not enabled:

![image](https://user-images.githubusercontent.com/567041/78181505-882c1a80-7432-11ea-92c8-81d63455c97b.png)

### Expected behaviour

When I make a post from a third-party client like Tusky (which doesn't allow specifying whether a post should federate) that is not in reply to another post and the above "default federation" setting is disabled, the status should not federate.

### Actual behaviour

Status posted from Tusky that are not in reply to another post will always federate.

I'm not super familiar with Ruby but if I had to chance a guess I'd say `nil` is returned and the rest of this method is never reached (and thus the default federation setting is never checked) when a client doesn't specify `local_only` and the post isn't in reply to anything.

https://github.com/hometown-fork/hometown/blob/1d70261350520887bd3127ffffc85de7e26c4ca9/app/services/post_status_service.rb#L88-L92

Note that this is a distinct issue from #23; the latter concerns a path for third-party clients to better support local-only posting, whereas this issue is about sensible default behaviours for third-party clients in the absence of that support.

### Specifications

Hometown v1.0.3

**Comment by dariusk** [comment]
Hi, sorry about the long delay on this. Pandemic hit me pretty hard (mentally) and I wasn't getting a lot of work done. I'm going to see what I can do here and hopefully have a fix by Monday in Hometown 1.0.4.

**Comment by dariusk** [comment]
It looks like I have a working fix! I'm running this on my own instance until Monday just to make sure there aren't unforeseen bugs but this will be in the 1.0.4 release. Thank you very much for this bug report, it was really helpful.
