### ISSUE TITLE
Incorrect database name in release note database backup instructions

### ISSUE THREAD

**Issue by OddBloke** [hometown-fork/hometown#54]
The command given is

```sh
pg_dump -Fc -U postgres postgres > name_of_the_backup.dump
```

but this actually backs up only the "postgres" database (which I think is the default DB; it only produces a 1.8 kilobyte dump file). My Mastodon database is called "mastodon_production" so

```sh
pg_dump -Fc -U postgres mastodon_production > name_of_the_backup.dump
```

is what I want (and produces a 55MB dump, which seems more apropos).

(Maybe I did something unusual during my installation, in which case I apologise for the noise!)

**Comment by ghost** [comment]
Hi,

Thanks for your report, I [updated the releases accordingly](https://github.com/hometown-fork/hometown/releases).
Closing now.
