### ISSUE TITLE
release v1.0.6+3.2.1?

### ISSUE THREAD

**Issue by ghost** [hometown-fork/hometown#552]
Hi,

Mastodon [v3.2.1](https://github.com/tootsuite/mastodon/releases/tag/v3.2.1) has been out for some time already, @dariusk would you consider releasing Hometown v1.0.6+3.2.1?
This minor release bring a lot of fixes that are needed by many users.

Thanks in advance

**Comment by ghost** [comment]
A small update: Mastodon [v3.2.2](https://github.com/tootsuite/mastodon/releases/tag/v3.2.2) was released yesterday.

**Comment by ghost** [comment]
And [v3.3.0](https://github.com/tootsuite/mastodon/releases/tag/v3.3.0) just came out.

**Comment by dariusk** [comment]
Thank you -- I've blocked off a few hours tomorrow to merge in 3.3.0.

**Comment by dariusk** [comment]
I've deployed this to Friend Camp. I've encountered some critical bugs which I'll be trying to squash this week. Once that's all working we'll have a release.

**Comment by ghost** [comment]
> I've deployed this to Friend Camp. I've encountered some critical bugs which I'll be trying to squash this week. Once that's all working we'll have a release.

Okay, thanks! Looking forward to deploy the future release to rage.love

In the meantime, if you want to share the minor releases burden you can maybe document the method you use to publish them. I or someone else will be able to do it too. :)

**Comment by dariusk** [comment]
That's a great idea. I will make some documentation on it. The hard part is always resolving the merge conflicts though. Some minor releases don't result in conflicts and those are easy, but there are usually some tough calls as to how to resolve differences in Hometown features versus vanilla Mastodon.

**Comment by dariusk** [comment]
There are lot more bugs than I was expecting, so this may be delayed until next week.

**Comment by ghost** [comment]
> There are lot more bugs than I was expecting, so this may be delayed until next week.

Thanks for the update. It's a shame so many things broke with these updates. Take your time to fix this!

**Comment by radiodario** [comment]
hey @dariusk let me know if i can help fix any of these - is there a tag or a list of issues? happy to take a couple of them!

**Comment by techknowlogick** [comment]
I see that friend.camp is running based on masto 3.3.0, is that the latest commit from this repo?

**Comment by dariusk** [comment]
Yes but several of the features, particularly ones around exclusive lists
are broken and I haven't had it in me to fix them. I welcome PRs, of course.

**Comment by dariusk** [comment]
Okay, I believe I have a working version up to date with Mastodon v.3.3.0, the latest release. I am running this version for a day on Friend Camp and then if everything goes well.... I'll do a release. Finally. aaaaa

**Comment by dariusk** [comment]
It happened! A release!

https://github.com/hometown-fork/hometown/releases/tag/v1.0.5%2B3.3.0
