### ISSUE TITLE
Add an icon when media has descriptions

### ISSUE THREAD

**Issue by lawremipsum** [hometown-fork/hometown#69]
See: https://github.com/lawremipsum/mspsocial-mastodon/pull/14

This feature by @divergentdave on MSP Social has been a popular and useful one. It allows all users to see, immediately, if an image has a description. It is a very lightweight quality-of-life customization that is popular with our users with and without sight impairments.

This promotes image description use on the server, makes users conscious of the feature, and allows them to easily do things like decide whether or not to engage with posts that don't have image descriptions.

(One way the implementation could be improved from what's currently running on MSP Social would be to make the description pop up when the icon is clicked, right now on hover it just displays a notice that there is a description.)

I'm posting this as a feature request simply because I don't have the git skills to offer it as a PR. If someone wants to walk me through how to make a patch to offer as a PR I'm happy to do that.

**Comment by divergentdave** [comment]
I have a branch ready to go for this at https://github.com/divergentdave/mspsocial-mastodon/tree/media-description-indicator-for-hometown! I was planning to wait for #68 before submitting it, but it can be rebased whenever.

**Comment by dariusk** [comment]
I'm going to implement the opposite of this -- an icon when media does _not_ have descriptions -- in v.1.10. My thinking here is that the default status of things should be described media, and it should alert people when that is not the case.
