### ISSUE TITLE
Inconsistent underlining for hashtag/mention prefixes

### ISSUE THREAD

**Issue by marrus-sh** [hometown-fork/hometown#7]
Upstream mastodon underlines links only on hover, including hashtags and mentions. When it does this, it only underlines the *contents* of the hashtag or mention (**not** including the `#`/`@` prefix).

Hometown underlines links always. However, when it does this, it underlines the *entirety* of the hashtag or mention (**including** the `#`/`@` prefix).

This produces inconsistent underlines, which may or may not include the prefix depending on whether or not the link is currently being hovered.

The relevant lines are here: https://github.com/hometown-fork/hometown/blob/hometown-dev/app/javascript/styles/mastodon/components.scss#L803-L811

For consistency, the `text-decoration: none` should be moved *outside* of the `:hover` (so that it always applies, and only the inner `<span>` is underlined), or it should be deleted (so that the whole thing is underlined always).

(Note the `.mention` class is used for *both* mentions and hashtags presently.)

**Comment by marrus-sh** [comment]
(note: if the first option is taken, then the styles for `span` will need to be moved outside the `:hover` as well. so, basically delete the `:hover {` and `}` lines.)

**Comment by emmawinston** [comment]
Will resolve this in my next round of theme bugfixes for hometown assuming @dariusk agrees. I do think the current underlining looks sloppy, on reflection. 

Relatedly, I am open to suggestions on link behaviour on hover/focus - currently, in some themes links change colour on hover but retain their underline, in others they retain their original colour but lose the underline on hover. I think the former is preferable.

**Comment by dariusk** [comment]
Fixed in #14, will be in the forthcoming 1.0.2 release.
