### ISSUE TITLE
Add ability to set default to local only as the default for new accounts

### ISSUE THREAD

**Issue by hazel-bohon** [hometown-fork/hometown#704]
As a hometown admin, it should be possible to set it so that by default new users default to local only posting. 

### Pitch

This enables admins to create more inwardly facing hometown instances, and seems in line with the core values of the Hometown fork. 

### Motivation

I think that for instances that really emphasize local posting this would be a huge win. This feature was originally suggested here: https://weirder.earth/@bound/105725986691505694

**Comment by exstral** [comment]
This has been implemented as a part of this bigger pull request with a simpler compose UI for local posts. Have a look if maybe that is interesting to you.
https://github.com/hometown-fork/hometown/pull/907

**Comment by dariusk** [comment]
Regardless of the #907 UI updates, I think this should be in a new version of Hometown. Flagging this as priority.

**Comment by rscmbbng** [comment]
Would love to have this feature!

**Comment by tillkruss** [comment]
I use this trigger to make that happen.

```sql
CREATE OR REPLACE FUNCTION set_default_federation() RETURNS TRIGGER AS
$BODY$
BEGIN
	INSERT INTO "public"."settings" ("var", "value", "thing_type", "created_at", "updated_at", "thing_id")
	VALUES ('default_federation', E'--- false\n', 'User', current_timestamp, current_timestamp, NEW.id);
	RETURN NEW;
END;
$BODY$
language plpgsql;
```

```sql
CREATE TRIGGER new_user_federation
AFTER INSERT ON "users"
FOR EACH ROW
EXECUTE PROCEDURE set_default_federation();
```

**Comment by dariusk** [comment]
This will be in the 1.1.0 release for sure.
