### ISSUE TITLE
Add weirder.earth to list of instances on hometown

### ISSUE THREAD

**Issue by hazel-bohon** [hometown-fork/hometown#705]
We recently migrated weirder.earth to Hometown, and would love to be included in the list of instances running Hometown on the wiki.

**Comment by ghost** [comment]
Hello,

Sure, what words would you like us to use as a small description?

**Comment by hazel-bohon** [comment]
I think our instance description would work great:

```
A community that skews thoughtful and weird. Everyone who abides by the code of conduct is welcome, thoughtful weirdos most of all! :)
```

**Comment by ghost** [comment]
Thanks, it's done: https://github.com/hometown-fork/hometown/wiki/Hometown-servers/7af9753c1bc01f6d8138e9b89377a670e3b0869c

**Comment by rscmbbng** [comment]
Hi @mthld could you also add post.lurk.org? I've already formatted the entry:

`|[post.lurk.org](https://post.lurk.org) |  post.lurk.org is an instance for discussions around cultural freedom, experimental, new media art, net and computational culture, and things like that. It is part of the family of artist-run infrastructures of lurk.org | yes (with review) |`

Many thanks :)

**Comment by ghost** [comment]
Hi @rscmbbng,

It's done: https://github.com/hometown-fork/hometown/wiki/Hometown-servers/0a740ff4ffb013610b17332fe2aebad3a132d79f

**Comment by rscmbbng** [comment]
thank you!
