### ISSUE TITLE
Email sender name should be instance name, not ‘Mastodon’

### ISSUE THREAD

**Issue by allinfinite** [hometown-fork/hometown#71]
### Especially for those of us using managed hosting, this simple personalization is very helpful.
![38A3CF62-7E23-4785-9884-F65D3BE31EFB](https://user-images.githubusercontent.com/2475429/88099383-cca10a80-cb36-11ea-8adc-c9dc2612ec70.jpeg)

**Comment by radiodario** [comment]
You can change this on `.env.production` using the `SMTP_FROM_ADDRESS` env var 

```
SMTP_FROM_ADDRESS='Amazing Club Person <notifications@yourserver.social>'
```
