### ISSUE TITLE
Update to mastodon 3.2.0

### ISSUE THREAD

**Issue by aphick** [hometown-fork/hometown#73]
Mastodon v3.2.0 has been out for a couple weeks now and contains several useful changes and a ton of fixes.

**Comment by ghost** [comment]
Hi,

It has been planned and should be released today. We were waiting for a new minor version correcting some bugs but Gargron doesn't seems to want to ship it for now.

Anyway, bear with us, it's coming. :)

**Comment by ghost** [comment]
Looks like it'll be tomorrow instead. We added a last time feature in the release, it's being tested as I write this.
