### ISSUE TITLE
An exclusive list becomes a regular list after its name is changed

### ISSUE THREAD

**Issue by MaybeThisIsRu** [hometown-fork/hometown#741]
### Expected behaviour

An exclusive list should stay exclusive in the event it is renamed.

### Actual behaviour

I had changed a list name earlier today. This was already marked as an exclusive list. Later (that is, now), I saw that toots from a user account showed up on my Home timeline. It looks like after the rename action, it became a non-exclusive list i.e. toots would appear both in the Home TL as well as the list TL.

### Steps to reproduce the problem

1. Create a list
2. Mark it as exclusive
2. Add someone (optionally?)
3. Change the title of the list and hit the checkmark for saving the changes
4. The flag for exclusive list stays on
5. Close the list dialog box
6. Go to Home
7. Open the list and click preferences -> edit for this list
8. The exclusive list toggle is off, and toots leak into the Home timeline

### Specifications

- Hometown v1.0.5+3.2.0
- Firefox v85.0.1 on Pop!_OS 20.04 LTS

---

Tried poking around but not much luck, unfortunately. Would love to see what solution anyone interested in tackling this comes up with.

**Comment by ghost** [comment]
Hello,

As your other bug report #777, can you take this upstream please?

Thanks!

**Comment by MaybeThisIsRu** [comment]
I'm not sure upstream would entertain this. There isn't any extra toggle (i.e. for exclusive lists) on vanilla Mastodon for them to look into it.

**Comment by ghost** [comment]
> I'm not sure upstream would entertain this. There isn't any extra toggle (i.e. for exclusive lists) on vanilla Mastodon for them to look into it.

Oh yes, my bad. Nevermind my comment and thanks for the bug report!
