### ISSUE TITLE
A filter applied to the Home timeline should also apply to exclusive lists.

### ISSUE THREAD

**Issue by MaybeThisIsRu** [hometown-fork/hometown#777]
### Expected behaviour

When I add a filter, such as for `@twitter.com`, to remove content from my Home timeline, I'd expect that such a toot also doesn't show up in an exclusive list.

### Actual behaviour

The filter that's applied to the home timeline (and public timeline) doesn't work in an exclusive list.

### Specifications

Hometown v1.0.5+3.2.0

**Comment by ghost** [comment]
Hello,

I don't believe we do any modifications on this part of Mastodon code, could you [take your issue upstream](https://github.com/tootsuite/mastodon/issues) please?

Thanks in advance,

**Comment by MaybeThisIsRu** [comment]
Ah, you're probably right, sorry. :)
