### ISSUE TITLE
Implement glitch-soc's "Show confirmation dialog before sending toots lacking media descriptions" feature

### ISSUE THREAD

**Issue by a-dows** [hometown-fork/hometown#778]
### Pitch

glitch-soc provides a checkbox in settings to warn a user before they post an image with no caption:

![image](https://user-images.githubusercontent.com/42701400/110667106-ec557380-8197-11eb-8d03-d206effd6c61.png)

Hometown should implement this feature.

### Motivation
This opt-in feature encourages users to remember to caption their images. Popular Mastodon client apps, like Toot, support this feature as well.

**Comment by FiXato** [comment]
Relevant pull request from glitch-soc repo: https://github.com/glitch-soc/mastodon/pull/691

Related issue for a similar warning for *boosting* uncaptioned media: https://github.com/glitch-soc/mastodon/pull/1098

**Comment by dariusk** [comment]
I will be implementing an indicator icon when posted media does not have alt text on it (so you can decide to not boost if your policy is to not boost media without alt text). Mastodon 3.5.2 introduced an icon that appears while you are posting media to remind you to add alt text, though it's not a popup. While I welcome the popup, I think that the upcoming change I plan to make, combined with the new Mastodon alt text hint, will suffice for now. I try to keep our fork not *too* different from upstream Mastodon where possible.
