### ISSUE TITLE
Improving local-only indicator styling

### ISSUE THREAD

**Issue by marrus-sh** [hometown-fork/hometown#8]
Sorry for the minor aesthetic quibbles, but I figure I might as well bring them up :P.

Right now the Local-Only indicator appears right next to the dropdown, not spaced like the other things in the status bar:

![image](https://user-images.githubusercontent.com/3212430/63636290-39a7d980-c622-11e9-9150-38b89132592c.png)

The reason for this is because the dropdown button is *not* a `.status__action-bar-button` (which has a right margin), but rather a `.status__action-bar-dropdown` (which does not). The code for styling that is here:

<https://github.com/hometown-fork/hometown/blob/hometown-dev/app/javascript/styles/mastodon/components.scss#L1107-L1110>

If you add `margin-right: 18px` to that ruleset, you can get equal spacing (see the rules for `.status__action-bar-button` on the immediately preceding lines):

![image](https://user-images.githubusercontent.com/3212430/63636341-e41ffc80-c622-11e9-8a59-7106509c42eb.png)

Alternatively, you can use `margin-right: auto` to right-justify the Local-Only icon:

![image](https://user-images.githubusercontent.com/3212430/63636350-0580e880-c623-11e9-9980-81de31b0c525.png)

(This is easier to miss on wide screens, but has the advantage of not looking like an actionable button.)

I think either of these approaches would be much clearer than the current one.

**Comment by marrus-sh** [comment]
(Actually, you will note in the third of my screenshots above, `margin-right: auto` does not *quite* right-justify the icon, because it still has its *own* `margin-right: 18px` (it *is* a `.status__action-bar-button`). If you wanted to eliminate that and get it truly flush right, you would need to add

```scss
&:last-child {
  margin-right: 0;
}
```

inside of the ruleset for `.status__action-bar-button` (lines 1103–1105):

![image](https://user-images.githubusercontent.com/3212430/63636465-8c829080-c624-11e9-9d82-a2f927389b97.png)

)

**Comment by emmawinston** [comment]
Will take a look at this in my next round of theme bugfixes along with tidying up link underlines (should be in the next few days). 

Thanks so much for how comprehensively and clearly you’ve documented this, also.

**Comment by dariusk** [comment]
Fixed in #15, will be in the forthcoming 1.0.2 release.
