### ISSUE TITLE
Typo in the character limit wiki page

### ISSUE THREAD

**Issue by ioistired** [hometown-fork/hometown#825]
Hi there. I was checking out your fork cause I want to check out Mastodon sysadmin. I noticed this page here: https://github.com/hometown-fork/hometown/wiki/Custom-max-toot-characters has a typo: 

```diff
- sudo systemctl restart mastodon-streaming.service mastodon-sidekiq.streaming mastodon-web.streaming
+ sudo systemctl restart mastodon-streaming.service mastodon-sidekiq.service mastodon-web.service
```

Cheers

**Comment by ghost** [comment]
Thanks for the report, fixed by [f770d00](https://github.com/hometown-fork/hometown/wiki/Custom-max-toot-characters/f770d00c3e6fe5377223dfd9cbb52b346decb2ad)!
