### ISSUE TITLE
add ausglam.space to list of servers

### ISSUE THREAD

**Issue by hughrun** [hometown-fork/hometown#890]
### Pitch

I am so excited! I have migrated ausglam.space to Hometown as of today. I'd like us to be added to [this wiki page](https://github.com/hometown-fork/hometown/wiki/Hometown-servers) please:

| Server | Description from About page | Accepting new users? |
| ---       |---                                             |---                                 |
| [Aus GLAM Space](https://ausglam.space) | Primarily for Australasian Galleries, Libraries, Archives, Museums and Records (GLAMR) people, and anyone else who wants to hang out with them. | yes (with review)    |

### Motivation

Other Hometowners will benefit by knowing that ausglam.space is also using this awesome fork!

**Comment by ghost** [comment]
Hi!

It's [done](https://github.com/hometown-fork/hometown/wiki/Hometown-servers/55d46d1e7b74f1551e0df6f216d0734b83e8f3d8).
