### ISSUE TITLE
Update the list of hometown servers in the wiki

### ISSUE THREAD

**Issue by MaybeThisIsRu** [hometown-fork/hometown#905]
Please add SmallCamp to the [list of Hometown servers](https://github.com/hometown-fork/hometown/wiki/Hometown-servers).

Server name: SmallCamp
Server URL: https://smallcamp.art/
Accepting new users: Yes, request from an existing member; reviewed upon account creation.

**Comment by ghost** [comment]
Done!

https://github.com/hometown-fork/hometown/wiki/Hometown-servers/0b9ec604a23b898012ca7703a61cca1dec0fa205

**Comment by MaybeThisIsRu** [comment]
Nice, thank you so much! :)
