### ISSUE TITLE
GitHub notification spammed by Dependabot

### ISSUE THREAD

**Issue by ghost** [hometown-fork/hometown#965]
Hi,

Each Monday morning I get my GitHub notifications spammed by Hometown's Dependabot:
<img width="415" alt="Screenshot 2021-05-24 at 10 46 39" src="https://user-images.githubusercontent.com/41020854/119322020-85ffcd80-bc7d-11eb-8040-fac91a0a59a5.png">

I think we have really no use for this, as Hometown's updates are taken from Mastodon and dependencies are already updated upstream. @dariusk would you please disable all Dependabots features on the relevant page?

https://github.com/hometown-fork/hometown/settings/security_analysis

Thanks in advance!

**Comment by mthld** [comment]
https://user-images.githubusercontent.com/41020854/126984100-7291c5e5-bbc4-4b3c-b0c1-4af560b928e4.mov

Still the case every Monday. :)

**Comment by weex** [comment]
Basically need to delete https://github.com/hometown-fork/hometown/blob/hometown-dev/.github/dependabot.yml or you can disable all patches per https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates

**Comment by dariusk** [comment]
Thank you! I have tried to figure this out and failed.
