### ISSUE TITLE
Consider publishing Docker Hub image?

### ISSUE THREAD

**Issue by decentral1se** [hometown-fork/hometown#969]
### Pitch

In order to use hometown more easily with Docker, it would be handy to have an "official" docker image published from this repository to something like `hometown-fork/hometown:<tag>` on https://hub.docker.com. There are a number of free services/integrations and the Dockerfile is already written from Mastodon side. It is just a matter of publishing one. It could even be done manually at first.

### Motivation

This would make it easier to use Hometown in the context of Docker. Right now you have to publish your own image afaict?

Also, it would handy to contribute together to the same place for any additional hometown specific work/docs/etc.

**Comment by decentral1se** [comment]
It might help with issues like https://github.com/hometown-fork/hometown/issues/650 also.

**Comment by decentral1se** [comment]
For now, I've published https://hub.docker.com/r/decentral1se/hometown but I can't offer much guarantee that it will be around for long. I had some help from the issues in building the container overin https://github.com/hometown-fork/hometown/issues/650#issuecomment-849890952 :clap: Btw, `v1.0.5+3.4.0` is not a valid Docker tag unfortunately, so I went with `v1.0.5_3.4.0`. 

There seems to be a bunch of work going into the Docker thing upstream over at https://github.com/tootsuite/mastodon/pulls?q=is%3Apr+is%3Aopen+docker so maybe it is something to ask there. Then you'd just have to create an account and switch the name of the container and re-use their upstream publishing setup?

**Comment by decentral1se** [comment]
Ah, this is already happening as it turns out:

![image](https://user-images.githubusercontent.com/1991377/120671144-63499200-c491-11eb-84d4-b34872b9c354.png)

I think you just need to follow https://docs.docker.com/docker-hub/builds/link-source/ to setup the integration.

**Comment by techknowlogick** [comment]
Sadly docker cloud doesn't offer builds for free accounts anymore, so this would either need to be done with github actions, or someone would need to fund an account on docker hub.

**Comment by decentral1se** [comment]
The co-op I'm a member of might be up for supporting if you want to avoid further Github lock-in:

- [autonomic.zone](https://autonomic.zone)
- [`helo@autonomic.zone`](mailto:helo@autonomic.zone)

We're hosting a Hometown instance for a group anyway so it makes sense to work together imho.

**Comment by Ramblurr** [comment]
> Sadly docker cloud doesn't offer builds for free accounts anymore, so this would either need to be done with github actions, or someone would need to fund an account on docker hub.

Quay.io, the alternative register run by RedHat (https://quay.io) offers free building and publishing of container images for github projects. It doesn't require github actions either.

**Comment by dariusk** [comment]
Unfortunately I try to avoid Docker in all things I do unless I am being paid a full time engineering salary to think about it. Sorry, it's just... not in the scope of things that I want to dedicate my free time to. Any Docker-related changes should be proposed upstream to Mastodon. I'm happy to pull them down but it's not in the scope of this fork.

**Comment by decentral1se** [comment]
Understandable @dariusk. I'll publish my own images then on the [co-op cloud side of things](https://coopcloud.tech/).
